11/23/24 devel@pi5-80:~/rp2350-freeRTOS/build $  echo $FREERTOS_KERNEL_PATH /home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel echo $PICO_SDK_PATH /home/devel/pico2/pico-sdk
devel@pi5-90:~/rp2350-freeRTOS/build $ cmake .. -DPICO_BOARD=pico2 -DPICO_PLATFORM=rp2350
Using FREERTOS_KERNEL_PATH from environment ('/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel')
Using PICO_SDK_PATH from environment ('/home/devel/pico2/pico-sdk')
PICO_SDK_PATH is /home/devel/pico2/pico-sdk
Target board (PICO_BOARD) is 'pico2'.
Using board configuration from /home/devel/pico2/pico-sdk/src/boards/include/boards/pico2.h
Pico Platform (PICO_PLATFORM) is 'rp2350-arm-s'.
-- Defaulting build type to 'Release' since not specified.
Defaulting compiler (PICO_COMPILER) to 'pico_arm_cortex_m33_gcc' since not specified.
Configuring toolchain based on PICO_COMPILER 'pico_arm_cortex_m33_gcc'
Defaulting PICO_GCC_TRIPLE to 'arm-none-eabi'
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
Build type is Release
-- Found Python3: /usr/bin/python3 (found version "3.11.2") found components: Interpreter
TinyUSB available at /home/devel/pico2/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /home/devel/pico2/pico-sdk/lib/btstack
cyw43-driver available at /home/devel/pico2/pico-sdk/lib/cyw43-driver
lwIP available at /home/devel/pico2/pico-sdk/lib/lwip
mbedtls available at /home/devel/pico2/pico-sdk/lib/mbedtls
Using FREERTOS_KERNEL_PATH from environment ('/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel')
Using  FREERTOS_CONFIG_FILE_DIRECTORY /home/devel/rp2350-freeRTOS/test-read-crc16
-- Configuring done
-- Generating done
-- Build files have been written to: /home/devel/rp2350-freeRTOS/build

make
[  0%] Building ASM object pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default.dir/compile_time_choice.S.obj
[  0%] Linking ASM executable bs2_default.elf
[  0%] Built target bs2_default
[  0%] Generating bs2_default.bin
[  1%] Generating bs2_default_padded_checksummed.S
[  1%] Built target bs2_default_padded_checksummed_asm
[  1%] Building C object klt-test/CMakeFiles/klt-test.dir/main.c.obj
/home/devel/rp2350-freeRTOS/klt-test/main.c:46:17: warning: array 'a' assumed to have one element
   46 | const short int a[];
      |                 ^
[  2%] Building C object klt-test/CMakeFiles/klt-test.dir/home/devel/pico2/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

[ 88%] Building C object test-read-crc16/CMakeFiles/test-read-crc16.dir/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c.obj
/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c: In function 'vPortSVCHandler_C':
/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c:1181:14: error: 'portSVC_START_SCHEDULER' undeclared (first use in this function)
 1181 |         case portSVC_START_SCHEDULER:
      |              ^~~~~~~~~~~~~~~~~~~~~~~
/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c:1181:14: note: each undeclared identifier is reported only once for each function it appears in
/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c: At top level:
/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c:1610:19: error: conflicting types for 'pxPortInitialiseStack'; have 'StackType_t *(StackType_t *, StackType_t *, void (*)(void *), void *)' {aka 'long unsigned int *(long unsigned int *, long unsigned int *, void (*)(void *), void *)'}
 1610 |     StackType_t * pxPortInitialiseStack( StackType_t * pxTopOfStack,
      |                   ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/include/FreeRTOS.h:101,
                 from /home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c:36:
/home/devel/rp2350-freeRTOS/test-read-crc16/FreeRTOS-Kernel/include/portable.h:133:23: note: previous declaration of 'pxPortInitialiseStack' with type 'StackType_t *(StackType_t *, void (*)(void *), void *)' {aka 'long unsigned int *(long unsigned int *, void (*)(void *), void *)'}
  133 |         StackType_t * pxPortInitialiseStack( StackType_t * pxTopOfStack,
      |                       ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [test-read-crc16/CMakeFiles/test-read-crc16.dir/build.make:1201: test-read-crc16/CMakeFiles/test-read-crc16.dir/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/port.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:2273: test-read-crc16/CMakeFiles/test-read-crc16.dir/all] Error 2
make: *** [Makefile:91: all] Error 2